apiVersion: v1
kind: Service
metadata:
  name: lb-grafana
  namespace: prometheus-stack
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - port: 80
    targetPort: 3000
